### PR TITLE
Make Angular a peer dependency

### LINKED ISSUE #14: Change "latest" angular dependency to avoid shrinkwrap issues
Hi!

In your [`package.json`](https://github.com/aleross/angular-segment-analytics/blob/0dbcd37f077902f47d15f9e820cc8a64f52d36e8/package.json#L23), you specify the angular dependency with the version of `latest`. Using the `latest` version has proven to be problematic because it doesn't seem like `npm` and the shrinkwrap file can handle resolving the dependencies correctly.

Here are a few issues that explain the issue in a bit more detail:
- https://github.com/npm/npm/issues/13496
- https://github.com/npm/npm/issues/10142

It also might make more sense to make angular a [peer dependency](https://nodejs.org/en/blog/npm/peer-dependencies/) instead of a normal dependency. That way, users of your module are required to also have `angular` listed as a dependency, but it doesn't lock down the version as harshly as a normal dependency. You can just specify `1.x.x` or `>= 1.2.0` or whatever minimum requirements you have.

I'd be happy to submit a PR if you let me know how you want to resolve the issue! Thanks for the great work!

### PR DESCRIPTION
**Pull request by robinjoseph08**
Fixes #14 

Make angular a peer dependency vs a normal dependency. To have a copy of angular for the tests, I added the installation of it in the .travis.yml, but I'm open to other suggestions (like adding it to the dev dependencies)!

### CODE REVIEW

**Comment by robinjoseph08** [comment]
@aleross have you gotten a chance to take a look yet? Thanks!

**Comment by aleross** [comment]
Looks great, thanks @robinjoseph08!

**Comment by robinjoseph08** [comment]
@aleross awesome, thanks! Any chance we can get a new version cut?

**Comment by robinjoseph08** [comment]
@aleross any update with a new version?

**Comment by aleross** [comment]
Sorry for the delay @robinjoseph08 - published a new version `1.1.12` with your PR's changes.

**Comment by robinjoseph08** [comment]
Thanks a ton @aleross!

**Pull request merged**
